% sort_coord_pixel
%
% 431-400 Year Long Project, LA1 - Medical Image Processing 2003
% Supervisor     :  Dr Lachlan Andrew
% Group Members  :  Alister Fong    78629   a.fong1@ugrad.unimelb.edu.au
%                   Lee Siew Teng   102519  s.lee1@ugrad.unimelb.edu.au
%                   Loh Jien Mei    103650  j.loh1@ugrad.unimelb.edu.au
%
% ===========================================================
% REQUIRES THE PROGRAMS "find_skel_ends" AND "plot_circle.m"
% DOWNLOAD FROM MATLAB CENTRAL!!!!!
% ===========================================================
%
% test_sort_coord.m (RUN THIS!!)
%   Test the 'sort_coord_pixel' function on a circle
% sort_coord_pixel.m (USE THIS!!)
%   Sorts the border pixels of an island in the clockwise or anti-clockwise direction
% place_values.m (USE THIS!!)
%   Assigned the values onto the image at the specified coordinates 
%   in the same order as specified. If the coordinates is in decimal, 
%   then it is rounded to the nearest pixel integer value
